/* ==========================================================================
   GRIMWICK WORKS — js/audio.js
   The Works, synthesised. Every sound is generated by WebAudio at runtime:
   no audio files, nothing to load, nothing to fail on file://.

   Nothing here is ever allowed to throw into the game loop.
   ========================================================================== */

var Audio = {

  ctx: null,
  master: null,
  enabled: false,
  ambient: { nodes: [], timers: [], station: null },
  _noise: null,

  init: function () {
    Audio.enabled = !!(S && S.settings && S.settings.audio);
  },

  setEnabled: function (on) {
    S.settings.audio = !!on;
    Audio.enabled = !!on;
    if (!on) Audio.stopAmbience();
    else { Audio.ensure(); if (S.time.phase === 'SHIFT' && S.factory.worked) Audio.stopAmbience(); }
  },

  volume: function () {
    var v = (S && S.settings && typeof S.settings.volume === 'number') ? S.settings.volume : 0.7;
    return Util.clamp(v, 0, 1);
  },

  ensure: function () {
    if (!Audio.enabled) return null;
    try {
      var AC = window.AudioContext || window.webkitAudioContext;
      if (!AC) return null;
      if (!Audio.ctx) {
        Audio.ctx = new AC();
        Audio.master = Audio.ctx.createGain();
        Audio.master.gain.value = 0.5 * Audio.volume();
        var comp = Audio.ctx.createDynamicsCompressor();
        comp.threshold.value = -18;
        comp.ratio.value = 8;
        Audio.master.connect(comp);
        comp.connect(Audio.ctx.destination);
      }
      if (Audio.ctx.state === 'suspended') Audio.ctx.resume();
      Audio.master.gain.value = 0.5 * Audio.volume();
      return Audio.ctx;
    } catch (e) { return null; }
  },

  /* browsers will not make a sound until the player has clicked something */
  unlock: function () { if (Audio.enabled) Audio.ensure(); },

  noise: function () {
    var ctx = Audio.ctx;
    if (Audio._noise) return Audio._noise;
    var len = ctx.sampleRate * 2;
    var buf = ctx.createBuffer(1, len, ctx.sampleRate);
    var d = buf.getChannelData(0);
    var last = 0;
    for (var i = 0; i < len; i++) {
      var white = Math.random() * 2 - 1;
      last = (last + 0.02 * white) / 1.02;      /* brown-ish: weight to the low end */
      d[i] = last * 3.2;
    }
    Audio._noise = buf;
    return buf;
  },

  /* ------------------------------------------------------------ one-shots */
  env: function (node, peak, attack, decay, when) {
    var t = when || Audio.ctx.currentTime;
    node.gain.cancelScheduledValues(t);
    node.gain.setValueAtTime(0.0001, t);
    node.gain.exponentialRampToValueAtTime(Math.max(0.0002, peak), t + attack);
    node.gain.exponentialRampToValueAtTime(0.0001, t + attack + decay);
  },

  tone: function (opts) {
    var ctx = Audio.ensure();
    if (!ctx) return;
    try {
      var o = ctx.createOscillator();
      var g = ctx.createGain();
      o.type = opts.type || 'sine';
      o.frequency.value = opts.freq || 220;
      if (opts.slideTo) {
        o.frequency.setValueAtTime(opts.freq, ctx.currentTime);
        o.frequency.exponentialRampToValueAtTime(opts.slideTo, ctx.currentTime + (opts.dur || 0.3));
      }
      var out = g;
      if (opts.filter) {
        var f = ctx.createBiquadFilter();
        f.type = opts.filter;
        f.frequency.value = opts.cutoff || 800;
        g.connect(f); f.connect(Audio.master);
      } else {
        g.connect(Audio.master);
      }
      o.connect(g);
      Audio.env(g, opts.gain || 0.15, opts.attack || 0.005, opts.dur || 0.25);
      o.start();
      o.stop(ctx.currentTime + (opts.attack || 0.005) + (opts.dur || 0.25) + 0.05);
      return out;
    } catch (e) { /* silence is acceptable; a crash is not */ }
  },

  burst: function (opts) {
    var ctx = Audio.ensure();
    if (!ctx) return;
    try {
      var src = ctx.createBufferSource();
      src.buffer = Audio.noise();
      src.loop = true;
      var f = ctx.createBiquadFilter();
      f.type = opts.filter || 'bandpass';
      f.frequency.value = opts.cutoff || 1200;
      f.Q.value = opts.q || 1;
      var g = ctx.createGain();
      src.connect(f); f.connect(g); g.connect(Audio.master);
      Audio.env(g, opts.gain || 0.12, opts.attack || 0.004, opts.dur || 0.2);
      if (opts.sweepTo) {
        f.frequency.setValueAtTime(opts.cutoff || 1200, ctx.currentTime);
        f.frequency.exponentialRampToValueAtTime(opts.sweepTo, ctx.currentTime + (opts.dur || 0.2));
      }
      src.start();
      src.stop(ctx.currentTime + (opts.dur || 0.2) + (opts.attack || 0.004) + 0.06);
    } catch (e) { }
  },

  /* the vocabulary of the game */
  thunk:  function () { Audio.tone({ type: 'square', freq: 78, dur: 0.09, gain: 0.10, filter: 'lowpass', cutoff: 300 }); },
  dial:   function () { Audio.tone({ type: 'square', freq: 320, dur: 0.05, gain: 0.05, filter: 'highpass', cutoff: 260 }); },
  paper:  function () { Audio.burst({ filter: 'highpass', cutoff: 2600, gain: 0.09, dur: 0.32, sweepTo: 5200 }); },
  coin:   function () { Audio.tone({ type: 'triangle', freq: 1180, dur: 0.18, gain: 0.06 }); Audio.tone({ type: 'triangle', freq: 1570, dur: 0.14, gain: 0.04 }); },
  press:  function () {
    Audio.tone({ type: 'sine', freq: 96, slideTo: 42, dur: 0.30, gain: 0.30, filter: 'lowpass', cutoff: 420 });
    Audio.burst({ filter: 'lowpass', cutoff: 900, gain: 0.16, dur: 0.16 });
  },
  spark:  function () { Audio.burst({ filter: 'bandpass', cutoff: 3400, q: 2.2, gain: 0.05, dur: 0.10, sweepTo: 6200 }); },
  pour:   function () { Audio.burst({ filter: 'bandpass', cutoff: 700, q: 0.8, gain: 0.10, dur: 0.9, sweepTo: 300 }); },
  tick:   function () { Audio.tone({ type: 'square', freq: 1600, dur: 0.03, gain: 0.025, filter: 'highpass', cutoff: 900 }); },
  hit:    function () {
    Audio.tone({ type: 'sine', freq: 160, slideTo: 48, dur: 0.5, gain: 0.28, filter: 'lowpass', cutoff: 500 });
    Audio.burst({ filter: 'lowpass', cutoff: 1400, gain: 0.18, dur: 0.28 });
  },
  flash:  function () {
    Audio.burst({ filter: 'highpass', cutoff: 400, gain: 0.34, dur: 1.0, sweepTo: 90 });
    Audio.tone({ type: 'sawtooth', freq: 620, slideTo: 40, dur: 1.2, gain: 0.16, filter: 'lowpass', cutoff: 1200 });
  },
  bell: function () {
    /* the five o'clock bell: two partials, long decay */
    Audio.tone({ type: 'sine', freq: 494, dur: 1.6, gain: 0.13 });
    Audio.tone({ type: 'sine', freq: 742, dur: 1.2, gain: 0.07 });
    Audio.tone({ type: 'sine', freq: 1231, dur: 0.7, gain: 0.03 });
  },

  /* ------------------------------------------------------------ ambience */
  ambience: function (station) {
    var ctx = Audio.ensure();
    if (!ctx) return;
    Audio.stopAmbience();
    Audio.ambient.station = station;
    try {
      /* the building itself: shafting, belts, the boiler two floors down */
      var rumble = ctx.createBufferSource();
      rumble.buffer = Audio.noise();
      rumble.loop = true;
      var lp = ctx.createBiquadFilter();
      lp.type = 'lowpass';
      lp.frequency.value = 190;
      var rg = ctx.createGain();
      rg.gain.value = 0.22;
      rumble.connect(lp); lp.connect(rg); rg.connect(Audio.master);
      rumble.start();

      var whine = ctx.createOscillator();
      var whine2 = ctx.createOscillator();
      whine.type = 'sawtooth'; whine.frequency.value = 58;
      whine2.type = 'sawtooth'; whine2.frequency.value = 87.5;
      var wf = ctx.createBiquadFilter();
      wf.type = 'lowpass'; wf.frequency.value = 380;
      var wg = ctx.createGain(); wg.gain.value = 0.05;
      whine.connect(wf); whine2.connect(wf); wf.connect(wg); wg.connect(Audio.master);
      whine.start(); whine2.start();

      var hiss = ctx.createBufferSource();
      hiss.buffer = Audio.noise();
      hiss.loop = true;
      var hf = ctx.createBiquadFilter();
      hf.type = 'bandpass'; hf.frequency.value = 2200; hf.Q.value = 0.6;
      var hg = ctx.createGain(); hg.gain.value = 0.02;
      hiss.connect(hf); hf.connect(hg); hg.connect(Audio.master);
      hiss.start();

      Audio.ambient.nodes = [rumble, whine, whine2, hiss, rg, wg, hg];

      /* and then whatever this particular floor does to the ear */
      var every = function (ms, fn, jitter) {
        var id = setInterval(function () {
          if (!Audio.enabled) return;
          if (jitter && Math.random() < jitter) return;
          fn();
        }, ms);
        Audio.ambient.timers.push(id);
      };

      if (station === 'STAMPING') every(1550, Audio.press);
      else if (station === 'CAP_BENCH') { every(430, Audio.tick, 0.25); every(3100, function () { Audio.tone({ type: 'triangle', freq: 880, dur: 0.06, gain: 0.02 }); }); }
      else if (station === 'GRINDING') { every(260, Audio.spark, 0.35); every(2400, function () { Audio.burst({ filter: 'bandpass', cutoff: 1500, q: 1.4, gain: 0.06, dur: 0.7 }); }); }
      else if (station === 'CASTING') { every(3400, Audio.pour); every(1100, function () { Audio.burst({ filter: 'lowpass', cutoff: 500, gain: 0.05, dur: 0.35 }); }, 0.4); }
    } catch (e) { }
  },

  stopAmbience: function () {
    var i;
    for (i = 0; i < Audio.ambient.timers.length; i++) clearInterval(Audio.ambient.timers[i]);
    Audio.ambient.timers = [];
    for (i = 0; i < Audio.ambient.nodes.length; i++) {
      try {
        var n = Audio.ambient.nodes[i];
        if (n.stop) n.stop();
        if (n.disconnect) n.disconnect();
      } catch (e) { }
    }
    Audio.ambient.nodes = [];
    Audio.ambient.station = null;
  },

  /* ---------------------------------------------------------- shift hooks */
  shiftStart: function (station) {
    if (!Audio.enabled) return;
    Audio.bell();
    Audio.ambience(station);
  },
  shiftEnd: function () {
    if (!Audio.enabled) return;
    Audio.stopAmbience();
    Audio.bell();
  },
  beat: function (kind) {
    if (!Audio.enabled) return;
    if (kind === 'cat') Audio.flash();
    else if (kind === 'hurt') Audio.hit();
    else if (kind === 'bad') Audio.thunk();
    else Audio.tick();
  },

  /* kept for the older call sites */
  chime: function () { Audio.coin(); }
};
