/* ==========================================================================
   GRIMWICK WORKS — js/audio.js
   The Works, synthesised. Every sound is generated by WebAudio at runtime:
   no audio files, nothing to load, nothing to fail on file://.

   Nothing here is ever allowed to throw into the game loop.
   ========================================================================== */

var Audio = {

  ctx: null,
  master: null,
  enabled: false,
  ambient: { nodes: [], timers: [], station: null },
  _noise: null,

  init: function () {
    Audio.enabled = !!(S && S.settings && S.settings.audio);
  },

  setEnabled: function (on) {
    S.settings.audio = !!on;
    Audio.enabled = !!on;
    if (!on) Audio.stopAmbience();
    else { Audio.ensure(); if (S.time.phase === 'SHIFT' && S.factory.worked) Audio.stopAmbience(); }
  },

  volume: function () {
    var v = (S && S.settings && typeof S.settings.volume === 'number') ? S.settings.volume : 0.7;
    return Util.clamp(v, 0, 1);
  },

  ensure: function () {
    if (!Audio.enabled) return null;
    try {
      var AC = window.AudioContext || window.webkitAudioContext;
      if (!AC) return null;
      if (!Audio.ctx) {
        Audio.ctx = new AC();
        Audio.master = Audio.ctx.createGain();
        Audio.master.gain.value = 0.5 * Audio.volume();
        var comp = Audio.ctx.createDynamicsCompressor();
        comp.threshold.value = -18;
        comp.ratio.value = 8;
        Audio.master.connect(comp);
        comp.connect(Audio.ctx.destination);
      }
      if (Audio.ctx.state === 'suspended') Audio.ctx.resume();
      Audio.master.gain.value = 0.5 * Audio.volume();
      return Audio.ctx;
    } catch (e) { return null; }
  },

  /* browsers will not make a sound until the player has clicked something */
  unlock: function () { if (Audio.enabled) Audio.ensure(); },

  noise: function () {
    var ctx = Audio.ctx;
    if (Audio._noise) return Audio._noise;
    var len = ctx.sampleRate * 2;
    var buf = ctx.createBuffer(1, len, ctx.sampleRate);
    var d = buf.getChannelData(0);
    var last = 0;
    for (var i = 0; i < len; i++) {
      var white = Math.random() * 2 - 1;
      last = (last + 0.02 * white) / 1.02;      /* brown-ish: weight to the low end */
      d[i] = last * 3.2;
    }
    Audio._noise = buf;
    return buf;
  },

  /* ------------------------------------------------------------ one-shots */
  env: function (node, peak, attack, decay, when) {
    var t = when || Audio.ctx.currentTime;
    node.gain.cancelScheduledValues(t);
    node.gain.setValueAtTime(0.0001, t);
    node.gain.exponentialRampToValueAtTime(Math.max(0.0002, peak), t + attack);
    node.gain.exponentialRampToValueAtTime(0.0001, t + attack + decay);
  },

  tone: function (opts) {
    var ctx = Audio.ensure();
    if (!ctx) return;
    try {
      var o = ctx.createOscillator();
      var g = ctx.createGain();
      o.type = opts.type || 'sine';
      o.frequency.value = opts.freq || 220;
      if (opts.slideTo) {
        o.frequency.setValueAtTime(opts.freq, ctx.currentTime);
        o.frequency.exponentialRampToValueAtTime(opts.slideTo, ctx.currentTime + (opts.dur || 0.3));
      }
      var out = g;
      if (opts.filter) {
        var f = ctx.createBiquadFilter();
        f.type = opts.filter;
        f.frequency.value = opts.cutoff || 800;
        g.connect(f); f.connect(Audio.master);
      } else {
        g.connect(Audio.master);
      }
      o.connect(g);
      Audio.env(g, opts.gain || 0.15, opts.attack || 0.005, opts.dur || 0.25);
      o.start();
      o.stop(ctx.currentTime + (opts.attack || 0.005) + (opts.dur || 0.25) + 0.05);
      return out;
    } catch (e) { /* silence is acceptable; a crash is not */ }
  },

  burst: function (opts) {
    var ctx = Audio.ensure();
    if (!ctx) return;
    try {
      var src = ctx.createBufferSource();
      src.buffer = Audio.noise();
      src.loop = true;
      var f = ctx.createBiquadFilter();
      f.type = opts.filter || 'bandpass';
      f.frequency.value = opts.cutoff || 1200;
      f.Q.value = opts.q || 1;
      var g = ctx.createGain();
      src.connect(f); f.connect(g); g.connect(Audio.master);
      Audio.env(g, opts.gain || 0.12, opts.attack || 0.004, opts.dur || 0.2);
      if (opts.sweepTo) {
        f.frequency.setValueAtTime(opts.cutoff || 1200, ctx.currentTime);
        f.frequency.exponentialRampToValueAtTime(opts.sweepTo, ctx.currentTime + (opts.dur || 0.2));
      }
      src.start();
      src.stop(ctx.currentTime + (opts.dur || 0.2) + (opts.attack || 0.004) + 0.06);
    } catch (e) { }
  },

  /* the vocabulary of the game */
  thunk:  function () { Audio.tone({ type: 'square', freq: 78, dur: 0.09, gain: 0.10, filter: 'lowpass', cutoff: 300 }); },
  dial:   function () { Audio.tone({ type: 'square', freq: 320, dur: 0.05, gain: 0.05, filter: 'highpass', cutoff: 260 }); },
  paper:  function () { Audio.burst({ filter: 'highpass', cutoff: 2600, gain: 0.09, dur: 0.32, sweepTo: 5200 }); },
  coin:   function () { Audio.tone({ type: 'triangle', freq: 1180, dur: 0.18, gain: 0.06 }); Audio.tone({ type: 'triangle', freq: 1570, dur: 0.14, gain: 0.04 }); },
  press:  function () {
    Audio.tone({ type: 'sine', freq: 96, slideTo: 42, dur: 0.30, gain: 0.30, filter: 'lowpass', cutoff: 420 });
    Audio.burst({ filter: 'lowpass', cutoff: 900, gain: 0.16, dur: 0.16 });
  },
  spark:  function () { Audio.burst({ filter: 'bandpass', cutoff: 3400, q: 2.2, gain: 0.05, dur: 0.10, sweepTo: 6200 }); },
  pour:   function () { Audio.burst({ filter: 'bandpass', cutoff: 700, q: 0.8, gain: 0.10, dur: 0.9, sweepTo: 300 }); },
  tick:   function () { Audio.tone({ type: 'square', freq: 1600, dur: 0.03, gain: 0.025, filter: 'highpass', cutoff: 900 }); },
  hit:    function () {
    Audio.tone({ type: 'sine', freq: 160, slideTo: 48, dur: 0.5, gain: 0.28, filter: 'lowpass', cutoff: 500 });
    Audio.burst({ filter: 'lowpass', cutoff: 1400, gain: 0.18, dur: 0.28 });
  },
  flash:  function () {
    Audio.burst({ filter: 'highpass', cutoff: 400, gain: 0.34, dur: 1.0, sweepTo: 90 });
    Audio.tone({ type: 'sawtooth', freq: 620, slideTo: 40, dur: 1.2, gain: 0.16, filter: 'lowpass', cutoff: 1200 });
  },
  bell: function () {
    /* the five o'clock bell: two partials, long decay */
    Audio.tone({ type: 'sine', freq: 494, dur: 1.6, gain: 0.13 });
    Audio.tone({ type: 'sine', freq: 742, dur: 1.2, gain: 0.07 });
    Audio.tone({ type: 'sine', freq: 1231, dur: 0.7, gain: 0.03 });
  },

  /* ------------------------------------------------------------ ambience */
  ambience: function (station) {
    var ctx = Audio.ensure();
    if (!ctx) return;
    Audio.stopAmbience();
    Audio.ambient.station = station;
    try {
      /* the building itself: shafting, belts, the boiler two floors down */
      var rumble = ctx.createBufferSource();
      rumble.buffer = Audio.noise();
      rumble.loop = true;
      var lp = ctx.createBiquadFilter();
      lp.type = 'lowpass';
      lp.frequency.value = 190;
      var rg = ctx.createGain();
      rg.gain.value = 0.22;
      rumble.connect(lp); lp.connect(rg); rg.connect(Audio.master);
      rumble.start();

      var whine = ctx.createOscillator();
      var whine2 = ctx.createOscillator();
      whine.type = 'sawtooth'; whine.frequency.value = 58;
      whine2.type = 'sawtooth'; whine2.frequency.value = 87.5;
      var wf = ctx.createBiquadFilter();
      wf.type = 'lowpass'; wf.frequency.value = 380;
      var wg = ctx.createGain(); wg.gain.value = 0.05;
      whine.connect(wf); whine2.connect(wf); wf.connect(wg); wg.connect(Audio.master);
      whine.start(); whine2.start();

      var hiss = ctx.createBufferSource();
      hiss.buffer = Audio.noise();
      hiss.loop = true;
      var hf = ctx.createBiquadFilter();
      hf.type = 'bandpass'; hf.frequency.value = 2200; hf.Q.value = 0.6;
      var hg = ctx.createGain(); hg.gain.value = 0.02;
      hiss.connect(hf); hf.connect(hg); hg.connect(Audio.master);
      hiss.start();

      Audio.ambient.nodes = [rumble, whine, whine2, hiss, rg, wg, hg];

      /* and then whatever this particular floor does to the ear */
      var every = function (ms, fn, jitter) {
        var id = setInterval(function () {
          if (!Audio.enabled) return;
          if (jitter && Math.random() < jitter) return;
          fn();
        }, ms);
        Audio.ambient.timers.push(id);
      };

      if (station === 'STAMPING') every(1550, Audio.press);
      else if (station === 'CAP_BENCH') { every(430, Audio.tick, 0.25); every(3100, function () { Audio.tone({ type: 'triangle', freq: 880, dur: 0.06, gain: 0.02 }); }); }
      else if (station === 'GRINDING') { every(260, Audio.spark, 0.35); every(2400, function () { Audio.burst({ filter: 'bandpass', cutoff: 1500, q: 1.4, gain: 0.06, dur: 0.7 }); }); }
      else if (station === 'CASTING') { every(3400, Audio.pour); every(1100, function () { Audio.burst({ filter: 'lowpass', cutoff: 500, gain: 0.05, dur: 0.35 }); }, 0.4); }
    } catch (e) { }
  },

  stopAmbience: function () {
    var i;
    for (i = 0; i < Audio.ambient.timers.length; i++) clearInterval(Audio.ambient.timers[i]);
    Audio.ambient.timers = [];
    for (i = 0; i < Audio.ambient.nodes.length; i++) {
      try {
        var n = Audio.ambient.nodes[i];
        if (n.stop) n.stop();
        if (n.disconnect) n.disconnect();
      } catch (e) { }
    }
    Audio.ambient.nodes = [];
    Audio.ambient.station = null;
  },


  /* ---------------------------------------------------------- stingers ---
     Four sounds the game uses as punctuation, and nothing else. */
  docketSlap: function () {
    /* paper on a counter, then the counter */
    Audio.burst({ filter: 'highpass', cutoff: 1800, gain: 0.14, dur: 0.14, sweepTo: 4200 });
    Audio.tone({ type: 'sine', freq: 132, slideTo: 64, dur: 0.22, gain: 0.16, filter: 'lowpass', cutoff: 500 });
  },
  knock: function () {
    /* three on a door that does not have to be opened */
    for (var i = 0; i < 3; i++) {
      (function (n) {
        setTimeout(function () {
          Audio.tone({ type: 'sine', freq: 168 - n * 8, slideTo: 74, dur: 0.16, gain: 0.22, filter: 'lowpass', cutoff: 420 });
          Audio.burst({ filter: 'lowpass', cutoff: 700, gain: 0.10, dur: 0.09 });
        }, n * 230);
      })(i);
    }
  },

  /* ------------------------------------------------------ ambient beds ---
     One per kind of place. Silence is the default state of this game; these
     are quiet, and they stop the moment you leave. */
  PLACE_BEDS: {
    works:     'factory',
    rows:      'room',
    market:    'street',
    store:     'room',
    pawn:      'room',
    apothecary:'room',
    ewe:       'tavern',
    chapel:    'chapel',
    railyard:  'street',
    garrison:  'street',
    cut:       'alley',
    street:    'street',
    workhouse: 'room'
  },

  place: function (nodeId) {
    if (!Audio.enabled) { Audio.stopAmbience(); return; }
    var bed = Audio.PLACE_BEDS[nodeId] || 'room';
    if (Audio.ambient.station === 'place:' + bed) return;   /* already there */
    var ctx = Audio.ensure();
    if (!ctx) return;
    Audio.stopAmbience();
    Audio.ambient.station = 'place:' + bed;
    try {
      var nodes = [];
      function noiseLayer(type, freq, q, gain) {
        var src = ctx.createBufferSource();
        src.buffer = Audio.noise();
        src.loop = true;
        var f = ctx.createBiquadFilter();
        f.type = type; f.frequency.value = freq; if (q) f.Q.value = q;
        var g = ctx.createGain(); g.gain.value = gain;
        src.connect(f); f.connect(g); g.connect(Audio.master);
        src.start();
        nodes.push(src, g);
        return g;
      }
      function every(ms, fn, skip) {
        var id = setInterval(function () {
          if (!Audio.enabled) return;
          if (skip && Math.random() < skip) return;
          fn();
        }, ms);
        Audio.ambient.timers.push(id);
      }

      if (bed === 'factory') {
        noiseLayer('lowpass', 190, 0, 0.20);
        every(1600, Audio.press);
        every(420, Audio.tick, 0.5);
      } else if (bed === 'street') {
        noiseLayer('lowpass', 320, 0, 0.10);
        /* rain, if it is raining */
        if (S.time.weather === 'rain' || S.time.weather === 'sleet') {
          noiseLayer('bandpass', 2600, 0.7, 0.10);
          noiseLayer('highpass', 5200, 0, 0.05);
        }
        every(5200, function () {
          Audio.tone({ type: 'triangle', freq: 300 + Math.random() * 120, dur: 0.09, gain: 0.02 });
        }, 0.4);
      } else if (bed === 'tavern') {
        noiseLayer('bandpass', 420, 0.5, 0.09);
        every(1700, function () {
          /* voices, none of them saying anything */
          Audio.tone({ type: 'sawtooth', freq: 100 + Math.random() * 90, dur: 0.3, gain: 0.022, filter: 'lowpass', cutoff: 620 });
        }, 0.2);
        every(6400, function () {
          Audio.tone({ type: 'triangle', freq: 720, dur: 0.14, gain: 0.03 });
        }, 0.35);
      } else if (bed === 'chapel') {
        noiseLayer('lowpass', 140, 0, 0.06);
        every(9000, function () {
          Audio.tone({ type: 'sine', freq: 196, dur: 2.2, gain: 0.035 });
        }, 0.3);
      } else if (bed === 'alley') {
        noiseLayer('lowpass', 240, 0, 0.08);
        every(4200, function () { Audio.burst({ filter: 'lowpass', cutoff: 500, gain: 0.03, dur: 0.4 }); }, 0.4);
      } else {
        /* a room: the fire if there is one, and the wall */
        noiseLayer('lowpass', 160, 0, 0.07);
        if (S.house.coal > 0) every(2600, function () {
          Audio.burst({ filter: 'bandpass', cutoff: 1400, q: 1.2, gain: 0.03, dur: 0.18 });
        }, 0.3);
      }
      Audio.ambient.nodes = nodes;
    } catch (e) { }
  },

  /* ----------------------------------------------------------- the cue ---
     One piece of music in the whole game, and it only plays when it is over.
     Nothing here is scored except grief. */
  endingCue: function () {
    if (!Audio.enabled || !(S.settings && S.settings.music)) return;
    var ctx = Audio.ensure();
    if (!ctx) return;
    Audio.stopAmbience();
    try {
      var t0 = ctx.currentTime + 0.15;
      /* a drone under it */
      var drone = ctx.createOscillator(), dg = ctx.createGain(), df = ctx.createBiquadFilter();
      drone.type = 'sine'; drone.frequency.value = 73.42;          /* D2 */
      df.type = 'lowpass'; df.frequency.value = 320;
      dg.gain.setValueAtTime(0.0001, t0);
      dg.gain.exponentialRampToValueAtTime(0.075, t0 + 2.2);
      dg.gain.exponentialRampToValueAtTime(0.0001, t0 + 15);
      drone.connect(df); df.connect(dg); dg.connect(Audio.master);
      drone.start(t0); drone.stop(t0 + 15.4);
      Audio.ambient.nodes.push(drone, dg);

      /* D minor, falling, unhurried, unresolved */
      var phrase = [
        [293.66, 0.0, 1.5], [349.23, 1.4, 1.4], [440.00, 2.7, 2.1],
        [392.00, 4.6, 1.5], [349.23, 5.9, 2.4], [293.66, 8.1, 2.0],
        [261.63, 10.0, 2.6], [220.00, 12.2, 3.0]
      ];
      for (var i = 0; i < phrase.length; i++) {
        var f = phrase[i][0], at = t0 + phrase[i][1], dur = phrase[i][2];
        var o = ctx.createOscillator(), g = ctx.createGain(), lp = ctx.createBiquadFilter();
        o.type = 'triangle';
        o.frequency.value = f;
        lp.type = 'lowpass'; lp.frequency.value = 1100;
        g.gain.setValueAtTime(0.0001, at);
        g.gain.exponentialRampToValueAtTime(0.062, at + 0.28);
        g.gain.exponentialRampToValueAtTime(0.0001, at + dur);
        o.connect(lp); lp.connect(g); g.connect(Audio.master);
        o.start(at); o.stop(at + dur + 0.1);
        Audio.ambient.nodes.push(o, g);
      }
    } catch (e) { }
  },

  /* ---------------------------------------------------------- shift hooks */
  shiftStart: function (station) {
    if (!Audio.enabled) return;
    Audio.bell();
    Audio.ambience(station);
  },
  shiftEnd: function () {
    if (!Audio.enabled) return;
    Audio.stopAmbience();
    Audio.bell();
  },
  beat: function (kind) {
    if (!Audio.enabled) return;
    if (kind === 'cat') Audio.flash();
    else if (kind === 'hurt') Audio.hit();
    else if (kind === 'bad') Audio.thunk();
    else Audio.tick();
  },

  /* kept for the older call sites */
  chime: function () { Audio.coin(); }
};
